"""Rename the count attribute in the Document class to document_count

Revision ID: 2a6d211f9d6b
Revises: ba1a4c539c99
Create Date: 2023-06-13 17:18:51.545567

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2a6d211f9d6b'
down_revision = 'ba1a4c539c99'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('document_count', sa.Integer(), nullable=True))
    op.drop_column('documents', 'count')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('count', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('documents', 'document_count')
    # ### end Alembic commands ###
