"""

Revision ID: a38e975e9974
Revises: a46d0d5b6205
Create Date: 2023-06-13 17:49:48.659530

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a38e975e9974'
down_revision = 'a46d0d5b6205'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
