"""f

Revision ID: a46d0d5b6205
Revises: b914c7e8fb92
Create Date: 2023-06-13 17:46:58.636837

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a46d0d5b6205'
down_revision = 'b914c7e8fb92'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
