"""update Document

Revision ID: b914c7e8fb92
Revises: 9222ee124d18
Create Date: 2023-06-13 17:37:24.890526

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b914c7e8fb92'
down_revision = '9222ee124d18'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('total_count', sa.Integer(), nullable=True))
    op.drop_column('documents', 'count')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('count', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('documents', 'total_count')
    # ### end Alembic commands ###
