"""Added a default value for the documents table count = 0

Revision ID: ba1a4c539c99
Revises: 64c6be01f0e0
Create Date: 2023-06-13 16:17:27.122817

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ba1a4c539c99'
down_revision = '64c6be01f0e0'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
