"""Added sms table

Revision ID: caa1b0698d0e
Revises: a38e975e9974
Create Date: 2023-06-14 12:16:28.810118

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'caa1b0698d0e'
down_revision = 'a38e975e9974'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('total_sms',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('total_send_sms', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('messages_sms',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('message', sa.String(length=250), nullable=True),
    sa.Column('from_phone', sa.String(), nullable=False),
    sa.Column('to_phone', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('total_sms_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['total_sms_id'], ['total_sms.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('messages_sms')
    op.drop_table('total_sms')
    # ### end Alembic commands ###
